//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Notes3.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My_Notes3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Notes.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string course {
            get {
                return ResourceManager.GetString("course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string flowDirection {
            get {
                return ResourceManager.GetString("flowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name:.
        /// </summary>
        public static string label_CourseName {
            get {
                return ResourceManager.GetString("label_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string label_LanguageSettings {
            get {
                return ResourceManager.GetString("label_LanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string label_newcourse {
            get {
                return ResourceManager.GetString("label_newcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Title:.
        /// </summary>
        public static string label_NoteTitle {
            get {
                return ResourceManager.GetString("label_NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email/Contact:.
        /// </summary>
        public static string label_ProfessorContact {
            get {
                return ResourceManager.GetString("label_ProfessorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor Name:.
        /// </summary>
        public static string label_ProfessorName {
            get {
                return ResourceManager.GetString("label_ProfessorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string label_removecourse {
            get {
                return ResourceManager.GetString("label_removecourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your course:.
        /// </summary>
        public static string label_selectcourse {
            get {
                return ResourceManager.GetString("label_selectcourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Add a New Image..
        /// </summary>
        public static string tooltip_addImage {
            get {
                return ResourceManager.GetString("tooltip_addImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Add a New Course..
        /// </summary>
        public static string tooltip_addNewCourse {
            get {
                return ResourceManager.GetString("tooltip_addNewCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Add a New Note..
        /// </summary>
        public static string tooltip_addNewNote {
            get {
                return ResourceManager.GetString("tooltip_addNewNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Remove the selected Course..
        /// </summary>
        public static string tooltip_deleteCourse {
            get {
                return ResourceManager.GetString("tooltip_deleteCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Remove the selected Image..
        /// </summary>
        public static string tooltip_deleteImage {
            get {
                return ResourceManager.GetString("tooltip_deleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here if you wish to Remove the selected Note/Notes..
        /// </summary>
        public static string tooltip_deleteNote {
            get {
                return ResourceManager.GetString("tooltip_deleteNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in this field to filter your contents..
        /// </summary>
        public static string tooltip_filter_notes {
            get {
                return ResourceManager.GetString("tooltip_filter_notes", resourceCulture);
            }
        }
    }
}
